### ISSUE TITLE
Text on submit answer button in Lessons question unreadable

### ISSUE THREAD

**Issue by joliet** [DukeLearningInnovation/duke-sakai-skins#206] opened 2020-08-04 22:09 UTC
When you add a question to a Lessons page, the text on submit answer button is unreadable. Button = dark blue, text = black.

<img width="427" alt="Lessons_Question_Button" src="https://user-images.githubusercontent.com/7387760/89350236-a5d9ec80-d67d-11ea-8fd1-c833addb6f6d.png">

**Comment by profmikegreene** [comment] 2020-08-05 01:59
Duplicate of #181 pervasive across all skins. Will fix.

**Closed by profmikegreene** 2020-08-05 01:59 UTC
Labels: duplicate
